(WIP) Add --target to each Dockerfile's FROM
alphagov/ckanext-datagovuk pull request #1777
Opened 2024-07-15 10:22 UTC by dj-maisy

## What?
This adds the `--platform` flag to each of the Dockerfiles to prepare us for multi-arch builds.

2024-07-15 17:24 UTC, kentsanggds requested changes
A few changes as some files are not needed so probably best removed

2024-07-15 17:24 UTC, kentsanggds commented on docker/ckan/2.10.3-core.Dockerfile
> +FROM --platform=$TARGETPLATFORM ubuntu:jammy
We can probably remove this file as we have upgraded to 2.10.4

2024-07-15 17:24 UTC, kentsanggds commented on docker/ckan/2.10.3.Dockerfile
> +FROM --platform=$TARGETPLATFORM ghcr.io/alphagov/ckan:2.10.3-base
This file can be removed as upgraded to 2.10.4

2024-07-15 17:24 UTC, kentsanggds commented on docker/ckan/2.9.9-base.Dockerfile
> +FROM --platform=$TARGETPLATFORM ghcr.io/alphagov/ckan:2.9.9-core
This file can be removed as upgraded to 2.10.4

2024-07-15 17:24 UTC, kentsanggds commented on docker/ckan/2.9.9-core.Dockerfile
> +FROM --platform=$TARGETPLATFORM ubuntu:focal
This file can be removed as upgraded to 2.10.4

2024-07-15 17:24 UTC, kentsanggds commented on docker/nginx/Dockerfile
> +FROM --platform=$TARGETPLATFORM nginx:stable-alpine
This is only used locally so probably don't need to update?

2024-07-15 17:24 UTC, kentsanggds commented on docker/solr/2.10.Dockerfile
> +FROM --platform=$TARGETPLATFORM solr:8
I'll have to test it out locally to see if this still works with CKAN 2.10.4, and then we will probably have to update the patch version for solr in the build image GHA

2024-07-26 14:25 UTC, kentsanggds approved these changes

2024-07-29 12:07 UTC, samsimpson1 approved these changes

2024-07-29 13:30 UTC, dj-maisy commented
I'm happy for this to be merged and then we can look at sorting out the Workflows.

2024-07-29 15:37 UTC, kentsanggds commented
Unfortunately once this is merged in it will affect the building of the base images, so I'm going to add some more commits to handle that in another branch to merge into this branch before merging to main

2024-07-29 17:27 UTC, merged